{{--
    ChatwootSync Widget Loader (auto-generated by WidgetController::widgetJs)

    Variables:
      $base_url           string  Chatwoot 实例 URL（不带末尾 /）
      $widget_token       string  Web Widget Website Token
      $identity_endpoint  string  /api/v1/plugin/chatwoot/widget-identity 绝对地址
      $has_hmac_secret    bool    后端是否已配置 hmac_secret

    设计要点 — "智能共存"：
      1. 同页已有 Chatwoot 官方嵌入脚本：本脚本只接管身份注入，不重复加载/run
      2. 同页已有其他客服厂商（Crisp/Intercom/Tawk/Zendesk/Freshchat）：本脚本
         直接退出，避免双气泡冲突（R2 加固）
      3. localStorage 'token' 这类通用 key 必须以 "Bearer " 前缀才被信任，
         防止其他 SDK 写入的无关字符串被误用为 auth token（R5 加固）

    JSON_HEX_* flags 防 </script> 注入逃逸（深度防御）。
--}}
// ChatwootSync widget @ {{ date('c') }}
(function (d, t) {
  var BASE_URL = {!! json_encode($base_url, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!};
  var TOKEN = {!! json_encode($widget_token, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!};
  var IDENTITY_URL = {!! json_encode($identity_endpoint, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!};
  var HAS_HMAC = {!! $has_hmac_secret ? 'true' : 'false' !!};

  if (window.__chatwootSyncLoaded) return;
  window.__chatwootSyncLoaded = true;

  // ---------- R2: 检测同页其他客服 widget，避免双气泡 ----------
  function detectCompetingChatWidget() {
    if (window.$crisp || window.CRISP_WEBSITE_ID) return 'Crisp';
    if (window.Intercom || window.intercomSettings) return 'Intercom';
    if (window.Tawk_API) return 'Tawk.to';
    if (window.zE || window.zESettings) return 'Zendesk';
    if (window.fcWidget) return 'Freshchat';
    if (window.LiveChatWidget) return 'LiveChat';
    return null;
  }

  // ---------- 检测：SDK 是否已被其他脚本处理 ----------
  function sdkHandledElsewhere() {
    if (window.chatwootSDK || window.$chatwoot || window.__chatwootSDKRunInProgress) return true;
    var scripts = d.getElementsByTagName('script');
    for (var i = 0; i < scripts.length; i++) {
      var src = scripts[i].src || '';
      if (src.indexOf('/packs/js/sdk.js') !== -1) return true;
    }
    return false;
  }

  // ---------- "SDK 就绪后回调"（多路径接住事件 + 永久指数退避轮询 + 60s 警告）----------
  function whenChatwootReady(cb) {
    var called = false;
    function safe() { if (called) return; called = true; cb(); }

    // 路径 A：事件——同时监听 window 和 document（不确定 SDK dispatch 到哪个）
    window.addEventListener('chatwoot:ready', safe);
    d.addEventListener('chatwoot:ready', safe);

    // R3: 60s 后还没就绪 → 一次性 console.warn 提示运维查 allowed_domains
    setTimeout(function () {
      if (!called && window.console && console.warn) {
        console.warn('[ChatwootSync] chatwoot:ready not fired after 60s — likely cause: this domain is not in the Chatwoot inbox allowed_domains list, or sdk.js failed to load');
      }
    }, 60000);

    // 路径 B：轮询兜底——250ms 起步、指数退避到 5s 封顶、不设上限
    var delay = 250;
    function tick() {
      if (called) return;
      if (window.$chatwoot && typeof window.$chatwoot.setUser === 'function') {
        safe();
        return;
      }
      delay = Math.min(delay * 1.5, 5000);
      setTimeout(tick, delay);
    }
    setTimeout(tick, delay);
  }

  // ---------- R5: token 探测，对通用 key 加 heuristic 校验 ----------
  // 通用 key（token / access_token）必须以 "Bearer " 开头才被信任，
  // 避免误用其他 SDK 写入的无关字符串
  var GENERIC_KEYS = { 'token': 1, 'access_token': 1 };
  var MIN_TOKEN_LENGTH = 20;  // Sanctum token 通常 40+ 字符

  function readToken() {
    var keys = [
      'xb.auth',         // Xboard 新版（值形如 "Bearer xxx"）
      'auth_data',       // Chatwoot SDK 默认 / v2board 旧版
      'access_token',    // 通用 OAuth-ish key（要求 Bearer 前缀）
      'token',           // 通用兜底（要求 Bearer 前缀）
    ];
    try {
      for (var i = 0; i < keys.length; i++) {
        var v = window.localStorage.getItem(keys[i]);
        if (!v || typeof v !== 'string') continue;

        var hasBearer = /^Bearer\s+/i.test(v);
        // 通用 key 必须 Bearer 前缀；命名 key（xb.auth / auth_data）可以裸 token
        if (GENERIC_KEYS[keys[i]] && !hasBearer) continue;

        var stripped = v.replace(/^Bearer\s+/i, '').trim();
        if (stripped.length < MIN_TOKEN_LENGTH) continue;

        return stripped;
      }
    } catch (e) {}
    return null;
  }

  // 并发守卫 + 代际计数 + 负面缓存（R1）：避免反复发送已被拒绝的 token
  var inFlight = false;
  var generation = 0;
  var lastRejectedToken = null;

  function applyIdentity() {
    var token = readToken();
    if (!token) return;
    if (inFlight) return;
    if (token === lastRejectedToken) return;  // R1: 这个 token 已被拒，别重试

    inFlight = true;
    var myGen = ++generation;

    fetch(IDENTITY_URL, {
      method: 'GET',
      headers: { 'Authorization': 'Bearer ' + token, 'Accept': 'application/json' },
      credentials: 'omit'
    })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (data) {
        if (myGen !== generation) return;
        if (!data) return;
        if (!data.authenticated) {
          lastRejectedToken = token;  // 记录拒绝，避免下次同 token 再 fetch
          return;
        }
        lastRejectedToken = null;  // 成功了清缓存（避免 token 轮换后被卡）
        if (!window.$chatwoot || typeof window.$chatwoot.setUser !== 'function') return;
        try {
          window.$chatwoot.setUser(data.identifier, {
            email: data.email,
            name: data.name,
            identifier_hash: data.identifier_hash
          });
        } catch (err) {
          if (window.console && console.warn) console.warn('[ChatwootSync] setUser failed', err);
        }
      })
      .catch(function (err) {
        if (window.console && console.warn) console.warn('[ChatwootSync] identity fetch failed', err);
      })
      .then(function () { inFlight = false; });
  }

  function bootIdentity() {
    if (!HAS_HMAC) {
      if (window.console && console.warn) {
        console.warn('[ChatwootSync] hmac_secret not configured on Xboard — widget running anonymously');
      }
      return;
    }
    whenChatwootReady(applyIdentity);
  }

  // ---------- 主流程 ----------
  // R2 优先：发现其他客服 widget 直接退出
  var competing = detectCompetingChatWidget();
  if (competing) {
    if (window.console && console.warn) {
      console.warn('[ChatwootSync] detected ' + competing + ' widget on this page — aborting to avoid double-launcher conflict. Remove either ' + competing + ' or the ChatwootSync widget.js include.');
    }
    return;
  }

  // 1. 立刻检测；如果已被处理，直接进入身份注入
  if (sdkHandledElsewhere()) {
    bootIdentity();
  } else {
    // 2. 未检测到——等 DOMContentLoaded 后再检测一次（兜底脚本顺序）
    var startSelfLoad = function () {
      if (sdkHandledElsewhere()) { bootIdentity(); return; }

      var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
      g.src = BASE_URL + '/packs/js/sdk.js';
      g.async = true;
      s.parentNode.insertBefore(g, s);
      g.onload = function () {
        if (!window.chatwootSDK) return;
        if (window.$chatwoot || window.__chatwootSDKRunInProgress) {
          bootIdentity();
          return;
        }
        window.__chatwootSDKRunInProgress = true;
        try {
          window.chatwootSDK.run({ websiteToken: TOKEN, baseUrl: BASE_URL });
        } catch (err) {
          if (window.console && console.warn) console.warn('[ChatwootSync] chatwootSDK.run failed', err);
        }
        bootIdentity();
      };
    };

    if (d.readyState === 'loading') {
      d.addEventListener('DOMContentLoaded', startSelfLoad);
    } else {
      startSelfLoad();
    }
  }

  // ---------- 监听登录态变化 ----------
  window.addEventListener('storage', function (e) {
    if (e.key === 'xb.auth' || e.key === 'auth_data' || e.key === 'token' || e.key === 'access_token') {
      try { applyIdentity(); } catch (err) {}
    }
  });

  // 同标签：SPA 登录后 localStorage 变化 storage 事件不触发——用轮询兜底
  var lastToken = readToken();
  setInterval(function () {
    var current = readToken();
    if (current && current !== lastToken) {
      lastToken = current;
      lastRejectedToken = null;  // token 变了，清负面缓存
      try { applyIdentity(); } catch (err) {}
    } else if (!current && lastToken) {
      lastToken = null;
    }
  }, 2000);
})(document, "script");
