{{--
    ChatwootSync Widget Loader (auto-generated by WidgetController::widgetJs)

    Variables:
      $base_url           string  Chatwoot 实例 URL（不带末尾 /）
      $widget_token       string  Web Widget Website Token
      $identity_endpoint  string  /api/v1/plugin/chatwoot/widget-identity 绝对地址
      $has_hmac_secret    bool    后端是否已配置 hmac_secret
--}}
// ChatwootSync widget @ {{ date('c') }}
(function (d, t) {
  var BASE_URL = {!! json_encode($base_url, JSON_UNESCAPED_SLASHES) !!};
  var TOKEN = {!! json_encode($widget_token) !!};
  var IDENTITY_URL = {!! json_encode($identity_endpoint, JSON_UNESCAPED_SLASHES) !!};
  var HAS_HMAC = {!! $has_hmac_secret ? 'true' : 'false' !!};

  if (window.__chatwootSyncLoaded) return;
  window.__chatwootSyncLoaded = true;

  // ---------- 1. 加载 Chatwoot SDK ----------
  var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
  g.src = BASE_URL + "/packs/js/sdk.js";
  g.defer = true;
  g.async = true;
  s.parentNode.insertBefore(g, s);

  g.onload = function () {
    if (!window.chatwootSDK) return;
    window.chatwootSDK.run({ websiteToken: TOKEN, baseUrl: BASE_URL });

    if (!HAS_HMAC) {
      if (window.console && console.warn) {
        console.warn('[ChatwootSync] hmac_secret not configured on Xboard — widget running anonymously');
      }
      return;
    }

    // ---------- 2. SDK 就绪后，从 localStorage 取 token 并 fetch 身份 ----------
    window.addEventListener('chatwoot:ready', function () { applyIdentity(); });
  };

  function applyIdentity() {
    var token = readToken();
    if (!token) return; // 未登录，匿名访客

    fetch(IDENTITY_URL, {
      method: 'GET',
      headers: { 'Authorization': 'Bearer ' + token, 'Accept': 'application/json' },
      credentials: 'omit'
    })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (data) {
        if (!data || !data.authenticated) return;
        try {
          window.$chatwoot.setUser(data.identifier, {
            email: data.email,
            name: data.name,
            identifier_hash: data.identifier_hash
          });
        } catch (err) {
          if (window.console && console.warn) console.warn('[ChatwootSync] setUser failed', err);
        }
      })
      .catch(function (err) {
        if (window.console && console.warn) console.warn('[ChatwootSync] identity fetch failed', err);
      });
  }

  /**
   * Xboard 前端的常见 token 存储位置（按优先级尝试）
   * - localStorage['auth_data']: 形如 "Bearer xxx" 或裸 token
   * - localStorage['token']: 历史 key
   */
  function readToken() {
    try {
      var keys = ['auth_data', 'token', 'access_token'];
      for (var i = 0; i < keys.length; i++) {
        var v = window.localStorage.getItem(keys[i]);
        if (v && typeof v === 'string') {
          return v.replace(/^Bearer\s+/i, '').trim();
        }
      }
    } catch (e) {}
    return null;
  }

  // SPA 登录/登出时 auth_data 写入或清除 → 重新 apply identity
  window.addEventListener('storage', function (e) {
    if (e.key === 'auth_data' || e.key === 'token' || e.key === 'access_token') {
      try { applyIdentity(); } catch (err) {}
    }
  });
})(document, "script");
